version: '3'

services:
  healthinsight-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # For development, you can mount the source code as a volume
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
